### ISSUE TITLE
Still Active?

### ISSUE THREAD

**Issue by jenke15** [exsmiley/AngryCartels#2]
I am super interested in this project! I was wondering if this project is on-going and will be continued to be developed or is it dying?

I have been trying to make something similar for awhile! However, I am quite knew when it comes to javascript, so I had nothing but trouble!

**Comment by exsmiley** [comment]
Hello. Are you saying you would like to contribute? I have sort of been working on it but I've been really busy.

**Comment by jenke15** [comment]
I would love to contribute! I am not sure what I am technically able to do but it wouldn't hurt to try!

**Comment by exsmiley** [comment]
Send me a list of your skills and let's take this offline of github. Email me at exsmiley@gmail.com
