### ISSUE TITLE
Unity player's username changes when entering a lobby

### ISSUE THREAD

**Issue by leaflet757** [exsmiley/AngryCartels#4]
After a valid user name is entered and written to the console correctly, the player will choose to enter a lobby but their socket.username will change to an integer when 'join game' is emitted. 

Current temporary fix: global temp username in synchronizer.js to store players name.

**Comment by exsmiley** [comment]
Check out https://github.com/4cade/AngryCartels/wiki/Socket.io-Messages to find out how to properly use the synchronizer. My guess is that you did not emit a 'join' message before trying to perform other operations.
